@startuml
class com.project.betr.Create_Workout_Activity {
~ TableLayout tableLayout
~ Button addRowButton
~ Button saveButton
~ EditText workoutNameText
~ ArrayList[] matrix
~ ArrayList<Button> removeRowList
~ ArrayList<Exercise> exerciseList
~ ArrayList<TableRow> rowsList
~ DBHelper dbHelper
~ FirebaseAuth fbauth
# void onCreate(Bundle)
+ void onClick(View)
- int dpToPx(int)
- void addRow()
- void init_matrix()
- boolean check_matrix_empty()
- void row_To_Exercise(int)
+ Workout create_workout()
- void removeRow(int)
}
class com.project.betr.RegisterActivity {
~ Button Register
~ EditText email_input
~ EditText password_input
~ EditText name_input
~ ProgressBar progressBar
~ FirebaseAuth fbAuth
~ DBHelper dbHelper
~ boolean Success
# void onCreate(Bundle)
+ void onClick(View)
- void inProgress(boolean)
- boolean isEmpty()
- void addUserToDB(User)
}
class com.project.betr.MenuActivity {
- ActivityMenuBinding binding
~ Toolbar toolbar
~ ImageView player_icon_image
~ int imageid
~ double userScore
~ String username
# void onCreate(Bundle)
# void onResume()
+ int returnPlayerIcon(double)
+ void onClick(View)
- int dpToPx(int)
}
class com.project.betr.MainActivity {
~ Button SignIn
~ TextView Register
~ EditText email_input
~ EditText password_input
~ ProgressBar progressBar
~ FirebaseAuth fbAuth
# void onCreate(Bundle)
+ void onClick(View)
- void inProgress(boolean)
- boolean isEmpty()
}
class com.project.betr.TimerActivity {
~ Button startTimer
~ TextView workoutName
~ ArrayList<Exercise> exerciseList
~ TableLayout tableLayout
# void onCreate(Bundle)
+ void onClick(View)
- void populate_table()
- TextView create_block(int,int)
- int dpToPx(int)
+ String formatTime(int)
- void createNotificationChannel()
}
class com.project.betr.Update_Workout_Activity {
~ TableLayout tableLayout
~ Button addRowButton
~ Button saveButton
~ EditText workoutNameText
~ ArrayList[] matrix
~ ArrayList<Button> removeRowList
~ ArrayList<Exercise> exerciseList
~ ArrayList<TableRow> rowsList
~ DBHelper dbHelper
~ FirebaseAuth fbauth
~ User currentUser
~ String workoutID
~ Workout currentWorkout
~ Button deleteExercise
~ AlertDialog.Builder builder
~ ArrayList<Button> graphButtons
~ boolean weightcheck
~ TextView codeText
# void onCreate(Bundle)
+ void onClick(View)
- int dpToPx(int)
- void addRow(String,boolean)
- void init_matrix()
- boolean check_matrix_empty()
- void row_To_Exercise(int)
+ Workout create_workout()
- void removeRow(int)
- Workout getCurrentWorkout()
- void populateRows()
+ void create_graph_dialog(String)
+ int getLargestWeight(ArrayList<Exercise>)
+ double getLargestScore(ArrayList<Exercise>)
+ void onCheckedChanged(RadioGroup,int)
}


com.project.betr.OnClickListener <|.. com.project.betr.Create_Workout_Activity
androidx.appcompat.app.AppCompatActivity <|-- com.project.betr.Create_Workout_Activity
com.project.betr.OnClickListener <|.. com.project.betr.RegisterActivity
android.app.Activity <|-- com.project.betr.RegisterActivity
com.project.betr.OnClickListener <|.. com.project.betr.MenuActivity
androidx.appcompat.app.AppCompatActivity <|-- com.project.betr.MenuActivity
com.project.betr.OnClickListener <|.. com.project.betr.MainActivity
android.app.Activity <|-- com.project.betr.MainActivity
com.project.betr.OnClickListener <|.. com.project.betr.TimerActivity
android.app.Activity <|-- com.project.betr.TimerActivity
com.project.betr.OnClickListener <|.. com.project.betr.Update_Workout_Activity
com.project.betr.OnCheckedChangeListener <|.. com.project.betr.Update_Workout_Activity
androidx.appcompat.app.AppCompatActivity <|-- com.project.betr.Update_Workout_Activity
@enduml